### PR TITLE
Update to go 1.14

### PR DESCRIPTION
**Pull request by jonnylangefeld**
* use [distroless](https://github.com/GoogleContainerTools/distroless) docker image for final stage
* run `go mod vendor`

### CODE REVIEW

**Comment by cxuu** [comment]
Thanks for your contribution!

Could you also update our CI config so we are testing with go.1.14 as well?

**Comment by jonnylangefeld** [comment]
@cxuu good point, seemed to be a version miss match before too (1.12 in ci vs. 1.11 in the docker image), that's why I didn't find it.
The `circleci/golang` images seem to be [legacy](https://circleci.com/docs/2.0/circleci-images/#next-gen-circleci-go-image) anyway, i updated it to the next gen image.

**Comment by cxuu** [comment]
I just slacked you but it seems slack was not fully setup for you. Could you rebase from master again? I just made a few commits. Thanks!

**Comment by jonnylangefeld** [comment]
Yes, exactly. I'm a new hire since this week and since we're all working from home, they'll send me a laptop in the mail tomorrow :)
Rebase is done!

**Pull request merged**
